name: 🚀 (DEV) Liberando versiones

on:
    push:
        branches:
            - release/next

jobs:
    ############ RELEASE ############
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: 'yarn'
                  registry-url: https://registry.npmjs.org/

            - run: corepack enable

            - name: Install NPM Dependencies
              run: yarn install --immutable --network-timeout 300000

            - name: Build Package
              run: yarn build:full

            - name: Release @bot-whatsapp/bot
              run: yarn node ./scripts/release.js --name=bot --version=  --token="${{ secrets.NPM_TOKEN }}"

            - name: Release @bot-whatsapp/cli
              run: yarn node ./scripts/release.js --name=cli --version=  --token="${{ secrets.NPM_TOKEN }}"

            - name: Release @bot-whatsapp/create-bot-whatsapp
              run: yarn node ./scripts/release.js --name=create-bot-whatsapp --version=  --token="${{ secrets.NPM_TOKEN }}"

            - name: Release @bot-whatsapp/database
              run: yarn node ./scripts/release.js --name=database --version=  --token="${{ secrets.NPM_TOKEN }}"

            - name: Release @bot-whatsapp/provider
              run: yarn node ./scripts/release.js --name=provider --version=  --token="${{ secrets.NPM_TOKEN }}"

            - name: Release @bot-whatsapp/contexts
              run: yarn node ./scripts/release.js --name=contexts --version=  --token="${{ secrets.NPM_TOKEN }}"

            - name: Release @bot-whatsapp/portal
              run: yarn node ./scripts/release.js --name=portal --version=  --token="${{ secrets.NPM_TOKEN }}"

            - name: GIT commit and push all changed files
              if: github.event_name == 'push'
              run: |
                  git config --global user.email "leifer.contacto@gmail.com"
                  git config --global user.name "Leifer Mendez"
                  git commit -a -m 'chore(version): dev release 🫡'
                  git push origin dev
